### ISSUE TITLE
Compiling for x86/ARM CE6

### ISSUE THREAD

**Issue by azhkprtw** [datadiode/browser#2]
Hi I’d love to try and test the browser but unfortunately I don’t possess a WEC2013 (CE8) device. 

Is there a chance that it’ll compile for CE6 x86? Obviously I know it’s a browser and there could be some huge differences between CE6 and CE8.

**Comment by datadiode** [comment]
If your platform supports EGL, it should be technically feasible.
The old compiler will probably cause headaches.

**Comment by azhkprtw** [comment]
I raised the question at HPC:Factor (forum for Windows CE devices) and we figured out my Thin Client most likely does not support EGL
https://www.hpcfactor.com/forums/forums/thread-view.asp?tid=21228&posts=7&start=1

Thank you for the reply though! Still impressed with your work!
